### ISSUE TITLE
Stack using linked list

### ISSUE THREAD

**Issue by Khushi-agarwal** [Algo-Phantoms/Algo-Tree#1604]
**Is your feature request related to a problem? Please describe.**
I want to implement stack data structure using linked list by adding functions like push and pop and display.

**Describe the solution you'd like**
A program to implement the same.

**Do you want to work on it**
C language.

Please @raksha009 @tarun26091999 assign me this.

**Comment by Ridhikalra** [comment]
**Is your feature request related to a problem ? Please describe.**
I would like to implement  Stack using linked list . I have already worked on it.

**Describe the solution you'd like.**
I will make a separate function of stack full and stack empty so that it will become easier to find whether the stack is empty or full.

**Do you want to work on it?**
yes, i can code the problem in C , C++, java and python.

Please assign this issue to me @raksha009 @tarun26091999

**Comment by Himanshi2997** [comment]
Is your feature request related to a problem ? Please describe.
I have already done this program in C++.

Describe the solution you'd like.
I will make different functions for checking whether stack is empty or full and to perform push, pop operations and for displaying the stack. 

Do you want to work on it?
I would like to contribute to this issue

I am a participant of GSSoC'21.
Will you please assign this issue to me @raksha009 @tarun26091999

**Comment by Rajashri14** [comment]
I want to work on this issue in Java. Please assign this issue to me.

**Comment by Khushi-agarwal** [comment]
@tarun26091999 It's been 12 days since I have opened this issue.Please assign this to me.

**Comment by Khushi-agarwal** [comment]
@Rohan27s please assign it to me.
